# Generated by Django 4.2.7 on 2023-12-07 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_post_thread_delete_message_delete_theme_post_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2023, 12, 7, 7, 48, 39, 916154, tzinfo=datetime.timezone.utc), max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
